import Link from 'next/link';import {requirePlatformAdmin} from '@/lib/server/supabase';import {PageEditor,PlanEditor} from '../cms-form';import {defaultPages,type PublicPage} from '@/lib/server/public-cms';
const originalSeedText='Learn how this platform supports your business. Our team can customise this content from the CMS.';
function suggestedEditorial(page:PublicPage):{page:PublicPage;suggested:boolean}{
 const original=defaultPages.find(candidate=>candidate.slug===page.slug);
 if(!original)return {page,suggested:false};
 const boilerplate=Array.isArray(page.sections)&&page.sections.length===1&&page.sections[0]?.body===originalSeedText;
 const homeOriginal=page.slug==='home'&&page.title==='Run your business with clarity. Grow with confidence.'&&page.description==='From customers and orders to accounting, stock and financial insights, bring the important parts of your business together in one thoughtful workspace.'&&Array.isArray(page.sections)&&page.sections.length===1&&page.sections[0]?.body==='No more switching between notebooks, scattered messages and separate spreadsheets.';
 if(!boilerplate&&!homeOriginal)return {page,suggested:false};
 return {page:{...original,slug:page.slug,published:page.published,description:homeOriginal?original.description:page.description,eyebrow:homeOriginal?original.eyebrow:page.eyebrow,title:homeOriginal?original.title:page.title},suggested:true};
}
export const dynamic='force-dynamic';
export default async function ContentAdmin(){const session=await requirePlatformAdmin();if(!session)return <main className="admin-access"><div className="card card-pad"><h1>Access restricted</h1><Link href="/login">Sign in</Link></div></main>;const {data:pages,error:pageError}=await session.client.from('public_site_pages').select('*').order('slug');const {data:plans,error:planError}=await session.client.from('public_site_plans').select('*').order('sort_order');const visiblePages=pages||[];const visiblePlans=plans||[];const missingPages=defaultPages.filter(p=>!visiblePages.some(actual=>actual.slug===p.slug));return <main className="admin-area"><header className="admin-header"><div><span className="badge badge-brand">Super Admin CMS</span><h1>Website Content & Pricing</h1><p>Manage public pages and plan cards. Edit the public pages and plan cards. Draft legal pages show a clearly marked review notice to visitors until you publish approved text.</p></div><Link className="btn" href="/admin">Back to branding</Link></header><>{(pageError||planError)&&<section className="card card-pad" role="alert"><h2>CMS data is unavailable</h2><p>Do not save replacement content until the database connection is repaired. Open <Link href="/admin/health">System diagnostics</Link>.</p></section>}<div className="cms-grid"><section><h2>Public Pages</h2>{!pageError&&!visiblePages.length&&<p className="muted">No CMS pages exist. Check migration 016 rather than editing placeholder content.</p>}{!pageError&&visiblePages.map(page=>{const entry=suggestedEditorial(page);return <details className="card card-pad cms-panel" key={page.slug}><summary>{entry.page.title} — /{page.slug}</summary>{entry.suggested&&<p className="muted small" role="status">We found the original starter copy. A revised editorial draft is loaded below; it will only replace database content after you review and save it.</p>}<PageEditor page={entry.page}/></details>})}{!pageError&&missingPages.map(page=><details className="card card-pad cms-panel" key={page.slug}><summary>New page: /{page.slug} (not yet in CMS)</summary><PageEditor page={page}/></details>)}</section><section><h2>Pricing Plans</h2>{!planError&&!visiblePlans.length&&<p className="muted">No pricing plans exist yet.</p>}{!planError&&visiblePlans.map(plan=><details className="card card-pad cms-panel" key={plan.id}><summary>{plan.name}</summary><PlanEditor plan={plan}/></details>) }{!planError&&<details className="card card-pad cms-panel"><summary>Add a new plan</summary><PlanEditor plan={{id:'new-plan',name:'New plan',price_label:'Contact sales',billing_label:'Custom',description:'',features:[],cta_label:'Contact us',cta_url:'/contact',sort_order:20,published:false}}/></details>}</section></div></></main>}
