import Link from 'next/link';
import {requirePlatformAdmin} from '@/lib/server/supabase';
import {getPlatformBrand} from '@/lib/server/branding';
import {savePlatformEmailTemplate} from './actions';
import {EmailTestForm} from './test-form';
import {renderBrandedEmail} from '@/lib/notifications-email';
export const dynamic='force-dynamic';
type Template={template_key:string;subject:string;heading:string;body_text:string;button_label:string;enabled:boolean};
export default async function EmailAdmin(){
 const session=await requirePlatformAdmin();if(!session)return <main className="admin-access"><h1>Administrator access required</h1><Link href="/login">Sign in</Link></main>;
 const [brand,result,deliveryResult]=await Promise.all([getPlatformBrand(),session.client.from('platform_email_templates').select('template_key,subject,heading,body_text,button_label,enabled').order('template_key'),session.client.from('platform_email_deliveries').select('id,template_key,recipient_email,status,provider_message_id,error_code,created_at').order('created_at',{ascending:false}).limit(30)]);
 return <main className="admin-area"><header className="admin-header"><div><span className="badge badge-brand">PLATFORM OWNER</span><h1>Email templates & notifications</h1><p>Manage platform notification copy. The branding shown below follows your Super Admin identity settings.</p></div><Link className="btn" href="/admin">Back to dashboard</Link></header>
 <section className="card card-pad" style={{marginBottom:20}}><h2>Current email branding</h2><p><strong>{brand.name}</strong> · {brand.support_email||'Set your support email in platform settings'}</p><p className="small muted">Logo: {brand.logo_url?'Configured':'Not configured'} · Primary colour: {brand.primary_color}</p><p className="small muted">Supabase Auth continues to use its existing email provider until you separately activate and test the signed Auth Hook. Live test sending is restricted to your own System Owner email address. Delivery must first be enabled and configured in Vercel.</p><p className="small muted">Resend sender: {process.env.RESEND_FROM_EMAIL||'Not configured'} · Delivery: {process.env.ENABLE_PLATFORM_EMAIL_DELIVERY==='true'?'Enabled':'Disabled'}</p></section>
 {result.error?<section className="card card-pad" role="alert">Unable to load templates. Apply migration 020 and verify administrator access.</section>:<div className="grid grid-2">{((result.data||[]) as Template[]).map(t=><section className="card card-pad" key={t.template_key}><h2>{t.template_key.replaceAll('_',' ')}</h2><form action={savePlatformEmailTemplate}><input type="hidden" name="template_key" value={t.template_key}/><label className="field">Email subject<input name="subject" required maxLength={200} defaultValue={t.subject}/></label><label className="field">Heading<input name="heading" maxLength={200} defaultValue={t.heading}/></label><label className="field">Email content<textarea name="body_text" rows={5} maxLength={10000} defaultValue={t.body_text}/></label><label className="field">Button label<input name="button_label" maxLength={100} defaultValue={t.button_label}/></label><label className="field"><input name="enabled" type="checkbox" defaultChecked={t.enabled}/> Enabled</label><button className="btn btn-primary" type="submit">Save template</button></form><details style={{marginTop:14}}><summary>Preview branded email</summary><iframe title={'Preview '+t.template_key} sandbox="" srcDoc={renderBrandedEmail(brand,{recipient:session.user.email||'',subject:t.subject,heading:t.heading,body:t.body_text,buttonLabel:t.button_label,actionUrl:'/admin/email'})} style={{width:'100%',height:400,border:'1px solid #e2e8f0',borderRadius:12,marginTop:10}} /></details><EmailTestForm templateKey={t.template_key} enabled={process.env.ENABLE_PLATFORM_EMAIL_DELIVERY==='true'}/></section>)}</div>}
 <section className="card card-pad" style={{marginTop:22}}><h2>Resend delivery history</h2><p className="muted small">Latest 30 administrator test attempts. Auth Hook emails are not included in these logs.</p>{deliveryResult.error?<p role="alert">Delivery logs unavailable. Apply migration 025.</p>:<div className="table-wrap"><table className="table"><thead><tr><th>Time</th><th>Template</th><th>Recipient</th><th>Status</th><th>Provider</th></tr></thead><tbody>{(deliveryResult.data||[]).map(item=><tr key={item.id}><td>{new Date(item.created_at).toLocaleString('en-NG')}</td><td>{item.template_key}</td><td>{item.recipient_email}</td><td>{item.status}{item.error_code?` · ${item.error_code}`:''}</td><td>{item.provider_message_id||'—'}</td></tr>)}</tbody></table></div>}{!deliveryResult.error&&!deliveryResult.data?.length&&<p className="muted">No test email sent yet.</p>}</section>
 </main>;
}
