"use client";
import {useActionState} from 'react';
import {saveTaxProfile,addSupply} from './actions';
const ACTIVITIES=[['retail','Retail'],['fashion','Fashion'],['food','Food & groceries'],['beauty','Beauty'],['manufacturing','Manufacturing'],['professional_services','Professional services'],['healthcare','Healthcare'],['education','Education'],['hospitality','Hospitality'],['technology','Technology'],['agriculture','Agriculture'],['construction','Construction'],['other','Other']];
const option=(v:string,l:string)=><option key={v} value={v}>{l}</option>;
type Profile={legal_structure?:string;turnover_band?:string;vat_registration_status?:string;employs_staff?:boolean|null;activities?:string[];goods_services?:string;notes?:string};
export function ProfileForm({id,profile}: {id:string;profile:Profile|null}){
 const [state,action,pending]=useActionState(saveTaxProfile,{error:'',success:''});
 return <form action={action} className="tax-form"><input type="hidden" name="business_id" value={id}/><div className="tax-fields"><div className="field"><label htmlFor="legal_structure">Legal structure</label><select name="legal_structure" id="legal_structure" defaultValue={profile?.legal_structure||'unknown'}>{[['unknown','Not sure yet'],['individual','Individual / sole proprietor'],['business_name','Registered business name'],['company','Limited company'],['partnership','Partnership'],['other','Other']].map(([v,l])=>option(v,l))}</select></div><div className="field"><label htmlFor="turnover_band">Approximate annual turnover</label><select id="turnover_band" name="turnover_band" defaultValue={profile?.turnover_band||'unknown'}>{[['unknown','Not sure yet'],['under_50m','Below ₦50 million'],['50m_100m','₦50m to ₦100m'],['over_100m','Above ₦100m']].map(([v,l])=>option(v,l))}</select></div><div className="field"><label htmlFor="vat_registration_status">VAT registration status</label><select id="vat_registration_status" name="vat_registration_status" defaultValue={profile?.vat_registration_status||'unknown'}>{[['unknown','Not sure'],['registered','Registered'],['not_registered','Not registered'],['pending','In progress']].map(([v,l])=>option(v,l))}</select></div><div className="field"><label htmlFor="employs_staff">Do you employ staff?</label><select id="employs_staff" name="employs_staff" defaultValue={profile?.employs_staff==null?'unknown':profile.employs_staff?'yes':'no'}>{[['unknown','Not sure / prefer later'],['yes','Yes'],['no','No']].map(([v,l])=>option(v,l))}</select></div></div><fieldset className="tax-fieldset"><legend>What does your business do? Select all that apply.</legend><div className="tax-activities">{ACTIVITIES.map(([v,l])=><label key={v} className="tax-choice"><input type="checkbox" name="activities" value={v} defaultChecked={profile?.activities?.includes(v)}/>{l}</label>)}</div></fieldset><div className="field"><label htmlFor="goods_services">Describe your goods and services</label><textarea id="goods_services" name="goods_services" rows={4} maxLength={2000} defaultValue={profile?.goods_services||''} placeholder="Example: uncooked rice, ready-to-eat meals, tailoring and imported adult clothing"/><span className="small muted">List distinct offerings. Different items may attract different tax treatments.</span></div><div className="field"><label htmlFor="notes">Other tax information (optional)</label><textarea id="notes" name="notes" rows={2} maxLength={1000} defaultValue={profile?.notes||''}/></div><button className="btn btn-primary" disabled={pending}>{pending?'Saving…':'Save tax discovery profile'}</button><Status state={state}/></form>;
}
export function SupplyForm({id}:{id:string}){const [state,action,pending]=useActionState(addSupply,{error:'',success:''});return <form action={action} className="tax-supply-form"><input type="hidden" name="business_id" value={id}/><div className="field"><label htmlFor="supply-name">Product or service name</label><input id="supply-name" name="name" minLength={2} maxLength={120} required placeholder="e.g. Fresh tomatoes"/></div><div className="field"><label htmlFor="supply-kind">Type</label><select id="supply-kind" name="supply_kind">{[['goods','Goods'],['services','Service'],['mixed','Package / Mixed']].map(([v,l])=>option(v,l))}</select></div><button className="btn btn-secondary" disabled={pending}>{pending?'Adding…':'Add for classification review'}</button><Status state={state}/></form>}
function Status({state}:{state:{error:string;success:string}}){return <>{state.error&&<p role="alert" className="negative small">{state.error}</p>}{state.success&&<p role="status" className="positive small">{state.success}</p>}</>}
