import {getWorkspace} from '@/lib/server/workspace';
import {ProfileForm,SupplyForm} from './forms';
export default async function TaxProfilePage(){
 const {client,businessId,role}=await getWorkspace();
 const {data:business}=await client.from('businesses').select('name').eq('id',businessId).maybeSingle();
 const {data:profile,error:profileError}=await client.from('business_tax_profiles').select('*').eq('business_id',businessId).maybeSingle();
 const {data:supplies,error:supplyError}=await client.from('business_supply_categories').select('id,name,supply_kind,proposed_vat_treatment').eq('business_id',businessId).order('created_at',{ascending:false});
 const missing=profileError||supplyError;
 return <div className="tax-page"><p className="muted small">BUSINESS PROFILE / TAX DISCOVERY</p><h1>Understand your business and taxes</h1><p className="muted">{business?.name||'Your business'} · Tell us about each activity. We will not automatically charge VAT based on your industry.</p><section className="tax-notice"><strong>Tax classification is not yet activated.</strong><p>This module collects information and queues items for review. It does not calculate, collect, file or determine tax liability. Legislation, eligibility and individual items must be verified first.</p></section>{missing&&<p role="alert" className="negative">Tax tables are unavailable. Apply migration 005 and reload to save your information.</p>}{role==='owner'?<><section className="tax-panel"><h2>1. Business details</h2><p className="muted small">You can update these answers whenever your business changes.</p><ProfileForm id={businessId} profile={profile}/></section><section className="tax-panel"><h2>2. Products and services</h2><p className="muted small">Add different offerings separately, even if they belong to one business category.</p><SupplyForm id={businessId}/></section></>:<section className="tax-panel"><p>Your business owner manages the tax discovery profile. You can view the review list below.</p></section>}<section className="tax-panel"><h2>3. Classification review list</h2>{supplies?.length?<div className="tax-list">{supplies.map(s=><div key={s.id} className="tax-list-row"><div><strong>{s.name}</strong><span className="small muted">{s.supply_kind}</span></div><span className="badge">{s.proposed_vat_treatment==='needs_review'?'Needs review':s.proposed_vat_treatment.replaceAll('_',' ')}</span></div>)}</div>:<p className="muted">No products or services have been submitted for classification yet.</p>}</section></div>;
}
