 'use server';
import {revalidatePath} from 'next/cache';import {z} from 'zod';import {requirePlatformAdmin} from '@/lib/server/supabase';
export type CmsState={ok:boolean;message:string};
const slug=z.string().regex(/^[a-z][a-z0-9-]{1,70}$/);
const text=z.string().trim().max(2000);
export async function saveCmsPage(_state:CmsState,form:FormData):Promise<CmsState>{const session=await requirePlatformAdmin();if(!session)return {ok:false,message:'Access denied'};const parsed=z.object({slug,title:z.string().trim().min(3).max(160),eyebrow:text,description:text,sections:z.string().max(25000),published:z.boolean()}).safeParse({slug:form.get('slug'),title:form.get('title'),eyebrow:form.get('eyebrow'),description:form.get('description'),sections:form.get('sections'),published:form.get('published')==='on'});if(!parsed.success)return {ok:false,message:'Check page fields and content length'};let sections;try{sections=JSON.parse(parsed.data.sections);if(!Array.isArray(sections)||sections.length>20||!sections.every(s=>s&&typeof s==='object'&&typeof s.heading==='string'&&typeof s.body==='string'&&s.heading.trim().length>0&&s.heading.length<=180&&s.body.trim().length>0&&s.body.length<=2000))throw new Error()}catch{return {ok:false,message:'Sections must be a JSON array of {heading,body} (max 20 sections)'}};
 if(parsed.data.published&&['privacy','terms','cookies'].includes(parsed.data.slug)&&sections.some((section:{body:string})=>/Learn how this platform supports your business|has not yet published|under review|awaiting approval|publication required/i.test(section.body))){return {ok:false,message:'Replace the legal draft placeholder with a reviewed, complete policy before publishing.'}}
 const {error}=await session.client.from('public_site_pages').upsert({...parsed.data,sections,updated_by:session.user.id},{onConflict:'slug'});if(error)return {ok:false,message:error.message};revalidatePath('/','layout');return {ok:true,message:'Page saved'};}
export async function saveCmsPlan(_state:CmsState,form:FormData):Promise<CmsState>{const session=await requirePlatformAdmin();if(!session)return {ok:false,message:'Access denied'};const parsed=z.object({id:slug,name:z.string().min(2).max(80),price_label:z.string().max(70),billing_label:text,description:text,features:z.string().max(5000),cta_label:z.string().max(90),cta_url:z.string().regex(/^\/[a-z0-9/-]*$/),sort_order:z.coerce.number().int().min(0).max(1000),published:z.boolean()}).safeParse({id:form.get('id'),name:form.get('name'),price_label:form.get('price_label'),billing_label:form.get('billing_label'),description:form.get('description'),features:form.get('features'),cta_label:form.get('cta_label'),cta_url:form.get('cta_url'),sort_order:form.get('sort_order'),published:form.get('published')==='on'});if(!parsed.success)return {ok:false,message:'Invalid plan fields'};const features=parsed.data.features.split('\n').map(s=>s.trim()).filter(Boolean).slice(0,30);const {error}=await session.client.from('public_site_plans').upsert({...parsed.data,features,updated_by:session.user.id},{onConflict:'id'});if(error)return {ok:false,message:error.message};revalidatePath('/','layout');return {ok:true,message:'Pricing plan saved'};}
