import 'server-only';
import {createClient} from '@supabase/supabase-js';
export type PublicPage={slug:string;title:string;eyebrow:string;description:string;sections:{heading:string;body:string}[];published:boolean};
export type PublicPlan={id:string;name:string;price_label:string;billing_label:string;description:string;features:string[];cta_label:string;cta_url:string;sort_order:number;published:boolean};
const defaults:Record<string,PublicPage>={
 home:{slug:'home',title:'Run your business with clarity. Grow with confidence.',eyebrow:'One workspace for your entire business',description:'From customers and orders to accounting, stock and financial insights, bring the important parts of your business together in one thoughtful workspace.',sections:[{heading:'Everything you need to keep business moving.',body:'No more switching between notebooks, scattered messages and separate spreadsheets.'}],published:true},
 features:{slug:'features',title:'Everything you need to run your business.',eyebrow:'THE PLATFORM',description:'From customer relationships and orders to accounting, tax records and clearer decisions, keep your business moving in one workspace.',sections:[{heading:'Sales and customer management',body:'Record orders, manage customers, track part payments and see outstanding balances.'},{heading:'Accounting and financial reports',body:'Keep ledgers, journal records and reports organised for professional review.'},{heading:'Products and inventory',body:'Manage your catalogue, service offerings and inventory movements.'},{heading:'Nigerian tax readiness',body:'Capture tax-relevant business information and prepare classified records for review. Automated statutory filing is not available.'},{heading:'Customer communication',body:'Organise messages and prepare customer communication templates. Outbound SMS and email require configured providers.'},{heading:'Business insights',body:'Understand recorded sales, collections, expenses and stock alerts.'}],published:true},
 solutions:{slug:'solutions',title:'A workspace for the way you do business.',eyebrow:'INDUSTRY SOLUTIONS',description:'Whether you sell goods, provide services or do both, organise daily work without a complicated setup.',sections:[{heading:'Retail and trading',body:'Orders, suppliers, inventory and outstanding customer payments.'},{heading:'Fashion and beauty',body:'Customer bookings, custom orders, deposits and delivery schedules.'},{heading:'Food and hospitality',body:'Sales records, purchases and expense visibility.'},{heading:'Professional services',body:'Quotations, invoices, client records and task tracking.'}],published:true},
 'how-it-works':{slug:'how-it-works',title:'Get organised in a few clear steps.',eyebrow:'HOW IT WORKS',description:'Start with what matters. Add more workflows as your business grows.',sections:[{heading:'1. Create your account',body:'Set up your secure login and business workspace.'},{heading:'2. Tell us about your business',body:'Choose your activities, products and services, and complete guided setup.'},{heading:'3. Record what happens',body:'Add customers, orders, payments, stock and expenses as you work.'},{heading:'4. See the bigger picture',body:'Review balances, financial records and business trends from one dashboard.'}],published:true},
 about:{slug:'about',title:'Built to make running a business clearer.',eyebrow:'ABOUT THE PLATFORM',description:'Practical software for growing businesses that need reliable records, simple workflows and room to scale.',sections:[{heading:'Our focus',body:'Put everyday operations, financial visibility and customer relationships in one practical workspace.'},{heading:'Designed for real work',body:'Useful on desktop and mobile, with an experience that supports business owners as well as accounting professionals.'}],published:true},
 resources:{slug:'resources',title:'Practical guidance for growing businesses.',eyebrow:'LEARN AND GROW',description:'Start with the basics of recordkeeping, pricing, bookkeeping and business registration.',sections:[{heading:'Keep clear financial records',body:'Separate revenue, customer collections, expenses and tax amounts in your business records.'},{heading:'Understand pricing',body:'Consider cost, margin, fees and applicable tax treatment before setting prices.'},{heading:'Prepare for registration',body:'Use official CAC and tax authority guidance to confirm current requirements.'}],published:true},
 contact:{slug:'contact',title:'We would love to hear from you.',eyebrow:'CONTACT',description:'Questions about the platform or interested in a business pilot? Reach our team using the contact details below.',sections:[{heading:'Sales and partnership enquiries',body:'Ask about business onboarding, commercial plans or partnership opportunities.'},{heading:'Customer support',body:'Use the published support email address for account assistance.'}],published:true},
 privacy:{slug:'privacy',title:'Privacy policy',eyebrow:'LEGAL',description:'Privacy information for the platform.',sections:[{heading:'Publication required',body:'The platform operator must publish a reviewed, complete privacy policy before collecting public customer data.'}],published:false},
 terms:{slug:'terms',title:'Terms of service',eyebrow:'LEGAL',description:'Terms governing use of the platform.',sections:[{heading:'Publication required',body:'The platform operator must publish reviewed terms before commercial launch.'}],published:false}
};
const demoPlans:PublicPlan[]=[{id:'starter',name:'Starter',price_label:'Contact us',billing_label:'Pilot access',description:'For sole traders and small businesses starting to organise daily records.',features:['Customers and orders','Manual payment tracking','Basic stock and business records'],cta_label:'Request access',cta_url:'/contact',sort_order:1,published:true},{id:'growth',name:'Growth',price_label:'Contact sales',billing_label:'Pricing to be announced',description:'For growing businesses that need deeper visibility and team workflows.',features:['Advanced reporting foundations','Team management','Accounting and tax records'],cta_label:'Talk to sales',cta_url:'/contact',sort_order:2,published:true}];
function publicClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return url&&key?createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}):null}
export async function getPublicPage(slug:string):Promise<PublicPage|null>{const fallback=defaults[slug]||null;const client=publicClient();if(!client)return fallback?.published?fallback:null;try{const {data,error}=await client.from('public_site_pages').select('slug,title,eyebrow,description,sections,published').eq('slug',slug).eq('published',true).maybeSingle();if(error)return fallback?.published?fallback:null;return data as PublicPage || null}catch{return fallback?.published?fallback:null}}
export async function getPublishedPlans():Promise<PublicPlan[]>{const client=publicClient();if(!client)return demoPlans;try{const {data,error}=await client.from('public_site_plans').select('id,name,price_label,billing_label,description,features,cta_label,cta_url,sort_order,published').eq('published',true).order('sort_order');return error?demoPlans:(data||[]) as PublicPlan[]}catch{return demoPlans}}
export const defaultPages=Object.values(defaults);
export const defaultPlans=demoPlans;
