import Link from 'next/link';
import {notFound} from 'next/navigation';
import type {Metadata} from 'next';
import {ArrowRight,ArrowUpRight,BookOpen,CheckCircle2,ChevronRight,ClipboardCheck,FileText,Info,LockKeyhole,Mail,ShieldCheck,Store,Users,Wallet,Boxes,BriefcaseBusiness,Scissors} from 'lucide-react';
import PublicNav from '@/components/public-nav';
import PublicFooter from '@/components/public-footer';
import {PublicHeroArt} from '@/components/public-hero-art';
import {getPlatformBrand} from '@/lib/server/branding';
import {getPublicPage} from '@/lib/server/public-cms';
export const revalidate=60;
const routes=['features','solutions','how-it-works','about','resources','contact','privacy','terms','cookies'];
const legalSlugs=['privacy','terms','cookies'];
const artwork=[Store,Scissors,BriefcaseBusiness,Users];
const featureIcons=[Users,Wallet,Boxes,FileText,ClipboardCheck,ShieldCheck];
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;if(!routes.includes(slug))return {};const [page,brand]=await Promise.all([getPublicPage(slug),getPlatformBrand()]);return {title:`${page?.title||'Information'} | ${brand.name}`,description:page?.description||brand.description,robots:legalSlugs.includes(slug)&&page?.reviewRequired?{index:false,follow:true}:undefined}}
export default async function PublicContent({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;if(!routes.includes(slug))notFound();
 const [brand,page]=await Promise.all([getPlatformBrand(),getPublicPage(slug)]);if(!page)notFound();
 const legal=legalSlugs.includes(slug);const compact=legal||slug==='contact';
 return <main id="site-main" className="marketing-site site-refresh"><PublicNav name={brand.name} logo={brand.logo_url} access={'guest'}/>
 <section className={`site-interior-hero site-interior-${slug} ${compact?'site-interior-compact':''}`}><div className="marketing-container site-interior-head"><div><div className="site-breadcrumb"><Link href="/">Home</Link><ChevronRight size={14}/><span>{slug.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ')}</span></div><span className="marketing-kicker">{page.eyebrow}</span><h1 className="public-page-title">{page.title}</h1><p>{page.description}</p>{!legal&&<div className="site-interior-hero-actions"><Link className="marketing-btn-primary" href={slug==='contact'&&brand.support_email?`mailto:${brand.support_email}`:'/signup'}>{slug==='contact'?'Contact support':'Get started'} <ArrowRight size={17}/></Link><Link href="/pricing" className="marketing-btn-outline">Explore plans <ArrowUpRight size={16}/></Link></div>}</div>{!compact&&<PublicHeroArt kind={slug as 'features'|'solutions'|'how-it-works'|'about'|'resources'}/>}</div></section>
 {legal?<section className="site-legal-section"><div className="marketing-container site-legal-layout"><aside className="site-legal-aside"><span className="marketing-kicker">LEGAL CENTRE</span><h2>Important information</h2><p>These pages are managed by the platform operator.</p><nav aria-label="Legal pages"><Link className={slug==='privacy'?'current':''} href="/privacy">Privacy notice</Link><Link className={slug==='terms'?'current':''} href="/terms">Terms of service</Link><Link className={slug==='cookies'?'current':''} href="/cookies">Cookies</Link></nav></aside><div className="site-legal-content">{page.reviewRequired&&<div className="site-legal-warning" role="status"><Info size={20}/><div><strong>This document is awaiting approval</strong><p>The platform operator has not yet published a reviewed version. The information below is a placeholder notice, not a binding or complete legal policy.</p></div></div>}{page.sections.map((s,i)=><section className="site-legal-item" key={i}><h2>{s.heading}</h2><p>{s.body}</p></section>)}<div className="site-legal-support"><Mail size={19}/><span>Need the current approved document? {brand.support_email?<a href={`mailto:${brand.support_email}`}>Contact support <ArrowUpRight size={14}/></a>:'Please contact the platform operator using the Contact page.'}</span></div></div></div></section>:
 <section className="marketing-section site-interior-sections"><div className="marketing-container"><div className="site-section-top"><div><span className="marketing-kicker">{slug==='solutions'?'CHOOSE YOUR WORKFLOW':slug==='how-it-works'?'THE JOURNEY':slug==='contact'?'HOW WE CAN HELP':'EXPLORE MORE'}</span><h2>{slug==='solutions'?'Built around the work you actually do.':slug==='how-it-works'?'A simpler process, step by step.':slug==='features'?'The everyday essentials, connected.':slug==='about'?'What drives our approach.':slug==='resources'?'Start with the fundamentals.':'Reach the right team.'}</h2></div><p>{slug==='solutions'?'From managing an order to following up on a payment, keep your day moving with fewer disconnected tools.':slug==='features'?'Explore the building blocks of a more organised business.':slug==='contact'?'Use the details published by the platform team to get in touch.':'Useful information to help you make the most of your workspace.'}</p></div><div className={`site-detail-grid ${slug==='solutions'?'site-detail-solutions':''}`}>{page.sections.map((s,i)=>{const Icon=slug==='solutions'?artwork[i%artwork.length]:featureIcons[i%featureIcons.length];return <article className="site-detail-card" key={i}><div className="site-detail-card-number">{String(i+1).padStart(2,'0')}</div><span className="marketing-feature-icon"><Icon size={22}/></span><h3>{s.heading}</h3><p>{s.body}</p><span className="site-detail-rule"/></article>})}</div>{slug==='contact'&&<div className="site-contact-action"><div><span className="marketing-kicker">OFFICIAL SUPPORT CHANNEL</span><h2>Let's start a conversation.</h2><p>{brand.support_email||'Our support address will be published by the platform administrator.'}</p></div>{brand.support_email?<a className="marketing-btn-primary" href={`mailto:${brand.support_email}`}>Send an email <ArrowRight size={18}/></a>:<span className="site-contact-pending">Support contact pending</span>}</div>}</div></section>}
 {!legal&&<section className="site-bottom-cta"><div className="marketing-container"><div className="site-cta-inner"><div><span className="marketing-kicker">MOVE FORWARD WITH CLARITY</span><h2>Make the everyday work feel lighter.</h2><p>Set up your workspace and start bringing the important details together.</p></div><Link href="/signup" className="marketing-btn-primary">Create your workspace <ArrowRight size={18}/></Link></div></div></section>}
 <PublicFooter name={brand.name} tagline={brand.tagline} email={brand.support_email}/></main>
}
