import {getViewerAccess} from '@/lib/server/viewer-access';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowRight,CheckCircle2} from 'lucide-react';
import PublicNav from '@/components/public-nav';
import PublicFooter from '@/components/public-footer';
import {getPlatformBrand} from '@/lib/server/branding';
import {getPublicPage} from '@/lib/server/public-cms';
export const dynamic='force-dynamic';
const routes=['features','solutions','how-it-works','about','resources','contact','privacy','terms'];
export default async function PublicContent({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(!routes.includes(slug))notFound();const [brand,page,access]=await Promise.all([getPlatformBrand(),getPublicPage(slug),getViewerAccess()]);if(!page)notFound();return <main className="marketing-site"><PublicNav name={brand.name} logo={brand.logo_url} access={access}/><section className="marketing-section marketing-section-muted"><div className="marketing-container marketing-section-heading"><span className="marketing-kicker">{page.eyebrow}</span><h1 className="public-page-title">{page.title}</h1><p>{page.description}</p></div></section><section className="marketing-section"><div className="marketing-container marketing-feature-grid">{page.sections.map((s,i)=><article className="marketing-feature" key={i}><span className="marketing-feature-icon"><CheckCircle2 size={23}/></span><h2>{s.heading}</h2><p>{s.body}</p></article>)}</div>{slug==='contact'&&<div className="marketing-container public-contact-block"><h2>Contact our team</h2><p>{brand.support_email||'Our support email has not yet been published.'}</p>{brand.support_email&&<a className="marketing-btn-primary" href={`mailto:${brand.support_email}`}>Send an email <ArrowRight size={18}/></a>}</div>}</section><section className="marketing-final"><div className="marketing-container"><span className="marketing-kicker">MOVE FORWARD</span><h2>Get more clarity in your business.</h2><p>Start with an organised workspace and grow at your pace.</p><Link href="/signup" className="marketing-btn-primary">Create your workspace <ArrowRight size={18}/></Link></div></section><PublicFooter name={brand.name} tagline={brand.tagline} email={brand.support_email}/></main>}
