'use server';
import {revalidatePath} from 'next/cache';
import {requireBusinessFeature} from '@/lib/server/authorization';
const field=(f:FormData,key:string,max=5000)=>String(f.get(key)||'').trim().slice(0,max);
async function owner(){const w=await requireBusinessFeature('campaigns');if(!w.allowed)throw new Error(w.reason);if(w.role!=='owner')throw new Error('Only business owners can manage campaigns');const {data:{user}}=await w.client.auth.getUser();if(!user)throw new Error('Sign in required');return {...w,user};}
export async function createSegment(f:FormData){const {client,businessId,user}=await owner();const name=field(f,'name',120),filter_kind=field(f,'filter_kind',30);if(name.length<2||!['all','with_email','with_phone'].includes(filter_kind))throw new Error('Invalid segment');const {error}=await client.from('contact_segments').insert({business_id:businessId,name,filter_kind,created_by:user.id});if(error)throw new Error('Unable to create segment');revalidatePath('/campaigns');}
export async function createCampaign(f:FormData){const {client,businessId,user}=await owner();const name=field(f,'name',120),body=field(f,'body'),subject=field(f,'subject',180),channel=field(f,'channel',10),segment_id=field(f,'segment_id',36);if(name.length<2||!body||!['sms','email'].includes(channel))throw new Error('Invalid campaign');if(channel==='email'&&!subject)throw new Error('Email subject required');const {data:segment}=await client.from('contact_segments').select('id').eq('business_id',businessId).eq('id',segment_id).maybeSingle();if(!segment)throw new Error('Choose a segment from this business');const {error}=await client.from('engagement_campaigns').insert({business_id:businessId,name,body,subject,channel,segment_id,created_by:user.id,status:'draft'});if(error)throw new Error('Unable to create campaign');revalidatePath('/campaigns');}
export async function previewCampaign(f:FormData){const {client,businessId}=await owner();const id=field(f,'campaign_id',36);const {data:c}=await client.from('engagement_campaigns').select('id').eq('business_id',businessId).eq('id',id).maybeSingle();if(!c)throw new Error('Campaign not found');const {error}=await client.rpc('engagement_preview_campaign',{p_campaign:id});if(error)throw new Error('Unable to generate recipient preview');revalidatePath('/campaigns');}
export async function createAutomation(f:FormData){const {client,businessId,user}=await owner();const name=field(f,'name',120),trigger_kind=field(f,'trigger_kind',40),channel=field(f,'channel',10),template_id=field(f,'template_id',36),delay_minutes=Number(field(f,'delay_minutes',8)||0);if(name.length<2||!['manual_review','order_created','payment_due','order_ready','birthday'].includes(trigger_kind)||!['sms','email'].includes(channel)||!Number.isInteger(delay_minutes)||delay_minutes<0||delay_minutes>43200)throw new Error('Invalid automation');const {data:t}=await client.from('communication_templates').select('id').eq('business_id',businessId).eq('id',template_id).eq('channel',channel).maybeSingle();if(!t)throw new Error('Choose a template matching the channel');const {error}=await client.from('engagement_automations').insert({business_id:businessId,name,trigger_kind,channel,template_id,delay_minutes,created_by:user.id,enabled:false});if(error)throw new Error('Unable to save automation');revalidatePath('/campaigns');}
