import {requireBusinessFeature} from '@/lib/server/authorization';
import Link from 'next/link';
import {getWorkspace} from '@/lib/server/workspace';
import {createSegment,createCampaign,createAutomation,previewCampaign} from './actions';
async function InternalProtectedPage(){const {client,businessId,role}=await getWorkspace();const [{data:segments,error:se},{data:campaigns,error:ce},{data:automations,error:ae},{data:templates},{data:previews}]=await Promise.all([
 client.from('contact_segments').select('id,name,filter_kind').eq('business_id',businessId).order('created_at',{ascending:false}),
 client.from('engagement_campaigns').select('id,name,channel,status,created_at').eq('business_id',businessId).order('created_at',{ascending:false}),
 client.from('engagement_automations').select('id,name,trigger_kind,channel,enabled').eq('business_id',businessId).order('created_at',{ascending:false}),
 client.from('communication_templates').select('id,name,channel').eq('business_id',businessId).in('channel',['email','sms']),
 client.from('engagement_message_queue').select('campaign_id,customer_id,channel,status').eq('business_id',businessId).limit(1000)
 ]);const isOwner=role==='owner';return <div className="campaign-page"><div className="page-head"><div><h1>Campaigns & Automations</h1><p>Plan customer engagement, preview recipients and create safe automation rules.</p></div><Link className="btn" href="/communications/settings">Message templates</Link></div>
 <div className="notice">Preview mode: no SMS or email is sent, no credits are used, and no automation executes until delivery controls and consent validation are implemented.</div>
 {(se||ce||ae)&&<p className="notice" role="alert">Campaign tables not available. Apply database migration 012 before using this page.</p>}
 <div className="grid grid-3" style={{margin:'18px 0'}}><div className="card card-pad"><div className="metric-label">Saved segments</div><div className="metric-value">{segments?.length||0}</div></div><div className="card card-pad"><div className="metric-label">Draft campaigns</div><div className="metric-value">{campaigns?.length||0}</div></div><div className="card card-pad"><div className="metric-label">Disabled automation rules</div><div className="metric-value">{automations?.length||0}</div></div></div>
 <div className="campaign-columns"><section className="card card-pad"><h2 className="section-title">Contact Segments</h2><p className="muted small">Select contacts from your existing customer list. These filters do not establish marketing consent.</p>{(segments||[]).map(s=><div className="list-row" key={s.id}><strong>{s.name}</strong><span className="badge">{s.filter_kind.replaceAll('_',' ')}</span></div>)}{!segments?.length&&<p className="muted small">No segments yet.</p>}{isOwner&&<form className="comms-form" action={createSegment}><label>Segment name<input name="name" required minLength={2} maxLength={120} placeholder="Customers with email"/></label><label>Contact filter<select name="filter_kind"><option value="all">All customers</option><option value="with_email">Customers with email</option><option value="with_phone">Customers with phone</option></select></label><button className="btn btn-primary">Create Segment</button></form>}</section>
 <section className="card card-pad"><h2 className="section-title">Campaign Drafts</h2><p className="muted small">Drafts are never sent by this version of the application.</p>{(campaigns||[]).map(c=><div className="list-row" key={c.id}><div><strong>{c.name}</strong><p className="muted small">{c.channel.toUpperCase()} · {c.status} · {new Date(c.created_at).toLocaleDateString('en-NG')}</p><span className="small muted">Preview contacts: {(previews||[]).filter(p=>p.campaign_id===c.id).length}{(previews||[]).length===1000?' (limited display)':''}</span></div>{isOwner&&<form action={previewCampaign}><input type="hidden" name="campaign_id" value={c.id}/><button className="btn" type="submit">Preview recipients</button></form>}</div>)}{!campaigns?.length&&<p className="muted small">No campaigns yet.</p>}{isOwner&&<form className="comms-form" action={createCampaign}><label>Campaign name<input name="name" required maxLength={120} placeholder="Order follow up"/></label><label>Channel<select name="channel"><option value="email">Email</option><option value="sms">SMS</option></select></label><label>Segment<select name="segment_id" required>{!segments?.length&&<option value="">Create a segment first</option>}{(segments||[]).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Email subject (required for email)<input name="subject" maxLength={180} placeholder="An update for you"/></label><label>Message<textarea name="body" required rows={4} maxLength={5000}/></label><button className="btn btn-primary" disabled={!segments?.length}>Save Campaign Draft</button></form>}</section></div>
 <section className="card card-pad" style={{marginTop:20}}><h2 className="section-title">Automation Rules</h2><p className="muted small">Rules are stored disabled. Activation requires a durable worker, approved consent policies, suppression rules, recipient checks and provider configuration.</p>{(automations||[]).map(a=><div className="list-row" key={a.id}><strong>{a.name}</strong><span className="badge">{a.trigger_kind.replaceAll('_',' ')} · {a.channel} · Disabled</span></div>)}{isOwner&&<form className="comms-form" action={createAutomation}><div className="campaign-fields"><label>Rule name<input name="name" required maxLength={120} placeholder="Upcoming payment reminder"/></label><label>Trigger<select name="trigger_kind"><option value="manual_review">Manual review</option><option value="order_created">New order</option><option value="payment_due">Payment due</option><option value="order_ready">Order ready</option><option value="birthday">Customer birthday</option></select></label><label>Channel<select name="channel"><option value="email">Email</option><option value="sms">SMS</option></select></label><label>Message template<select name="template_id" required><option value="">Select a template</option>{(templates||[]).map(t=><option key={t.id} value={t.id}>{t.name} ({t.channel})</option>)}</select></label><label>Delay in minutes<input name="delay_minutes" type="number" min="0" max="43200" defaultValue="0"/></label></div><button className="btn btn-primary" disabled={!templates?.length}>Save Disabled Automation</button></form>}</section></div>}

export default async function GuardedPage(){
 const check=await requireBusinessFeature('campaigns');
 if(!check.allowed)return <section className="tax-page"><h1>Access restricted</h1><p role="alert">{check.reason}</p><a className="btn" href="/upgrade">View available plans</a></section>;
 return <InternalProtectedPage/>;
}
