import {Suspense} from 'react';
import Link from 'next/link';
import {loadBusinessInsights} from '@/lib/insights/server';
import {money} from '@/lib/format';
import {AlertTriangle,ArrowUpRight,BarChart3,ClipboardList,CreditCard,Package,Plus,Receipt,TrendingUp,Users,Wallet} from '@/components/icons';
export const dynamic='force-dynamic';
const amount=(kobo:number)=>money(kobo/100);
const safePercent=(current:number,previous:number)=>previous>0?Math.round((current-previous)/previous*100):null;
const barWidth=(value:number,maximum:number)=>maximum>0?Math.max(0,Math.min(100,(Math.max(0,value)/maximum)*100)):0;
export default function Dashboard(){
 return <Suspense fallback={<div className="business-home" aria-busy="true" aria-label="Loading private business analytics">
  <div className="business-home-heading"><div><span className="business-eyebrow">WORKSPACE OVERVIEW</span><h1>Business dashboard</h1><p>Preparing your latest records…</p></div><div className="business-heading-actions"><Link href="/orders/new" className="btn btn-primary">New order</Link></div></div>
  <div className="business-stat-grid" aria-hidden="true">{['Sales','Payments','Outstanding','Expenses'].map(x=><section className="business-stat" key={x}><div className="metric-label">{x}</div><div className="business-stat-number">—</div><div className="small muted">Loading secure totals…</div></section>)}</div>
  <div className="business-quick-panel"><h2>Quick actions</h2><div className="business-quick-links"><Link href="/orders/new">Create order</Link><Link href="/customers/new">Add customer</Link><Link href="/payments">Payments</Link></div></div>
 </div>}><DashboardContent/></Suspense>;
}
async function DashboardContent(){
 const {current:c,previous:p,insights}=await loadBusinessInsights();
 const metrics=[
  {label:'Sales this month',value:amount(c.sales),detail:'Recorded order value',icon:TrendingUp,change:safePercent(c.sales,p.sales)},
  {label:'Payments received',value:amount(c.received),detail:'Completed payments this month',icon:CreditCard,change:safePercent(c.received,p.received)},
  {label:'Outstanding balances',value:amount(c.outstanding),detail:'Across recorded open orders',icon:Receipt,change:null},
  {label:'Expenses this month',value:amount(c.expenses),detail:'Paid expense records',icon:Wallet,change:safePercent(c.expenses,p.expenses)}
 ];
 const comparisons=[{label:'Sales',previous:p.sales,current:c.sales},{label:'Payments received',previous:p.received,current:c.received},{label:'Expenses',previous:p.expenses,current:c.expenses}];
 const maximum=Math.max(...comparisons.flatMap(row=>[row.previous,row.current]),0);
 return <div className="business-home">
  <div className="business-home-heading"><div><span className="business-eyebrow">WORKSPACE OVERVIEW</span><h1>Business dashboard</h1><p>Keep track of sales, money received and the work that needs your attention.</p></div><div className="business-heading-actions"><Link href="/customers/new" className="btn"> <Users size={16}/> Add customer</Link><Link href="/orders/new" className="btn btn-primary"><Plus size={16}/> New order</Link></div></div>
  <div className="business-overview-note"><span className="business-overview-note-icon"><BarChart3 size={19}/></span><div><strong>Live operational overview</strong><p>Figures reflect recorded business activity. They are not audited profit, bank balances or a substitute for reconciled financial statements.</p></div><Link href="/reports">View reporting <ArrowUpRight size={16}/></Link></div>
  <div className="business-stat-grid">{metrics.map(({label,value,detail,icon:Icon,change})=><section className="business-stat" key={label}><div className="business-stat-top"><span>{label}</span><span className="business-stat-icon"><Icon size={19}/></span></div><strong className="business-stat-number">{value}</strong><div className="business-stat-detail"><span>{detail}</span>{change!==null&&<span className={'business-stat-change'+(change<0?' is-negative':'')}>{change>0?'+':''}{change}% vs prior month</span>}</div></section>)}</div>
  <div className="business-small-stats"><Link href="/orders"><span className="business-small-stats-icon"><ClipboardList size={19}/></span><span><strong>{c.orders}</strong><small>Orders this month</small></span><ArrowUpRight size={17}/></Link><Link href="/inventory"><span className="business-small-stats-icon warn"><Package size={19}/></span><span><strong>{c.lowStock.length}</strong><small>Low stock alerts</small></span><ArrowUpRight size={17}/></Link><Link href="/invoices"><span className="business-small-stats-icon"><Receipt size={19}/></span><span><strong>Invoices</strong><small>Review issued documents</small></span><ArrowUpRight size={17}/></Link></div>
  <div className="business-dashboard-columns"><section className="business-dashboard-panel"><div className="business-panel-heading"><div><span className="business-eyebrow">PERFORMANCE</span><h2>Monthly comparison</h2><p>Current month compared with the previous month.</p></div><Link href="/reports" className="business-inline-link">Reports <ArrowUpRight size={15}/></Link></div><div className="business-chart-legend"><span><i className="business-legend-previous"/>Previous</span><span><i className="business-legend-current"/>Current</span></div><div className="business-bars">{comparisons.map(row=><div className="business-bar-row" key={row.label}><div className="business-bar-heading"><strong>{row.label}</strong><span>{amount(row.current)}</span></div><div className="business-bar-track" role="img" aria-label={`${row.label}: prior ${amount(row.previous)}, current ${amount(row.current)}`}><div className="business-bar-previous" style={{width:`${barWidth(row.previous,maximum)}%`}}/><div className="business-bar-current" style={{width:`${barWidth(row.current,maximum)}%`}}/></div></div>)}</div>{maximum===0&&<p className="small muted">No amounts recorded for these periods yet.</p>}</section>
  <section className="business-dashboard-panel"><div className="business-panel-heading"><div><span className="business-eyebrow">ACTION CENTRE</span><h2>Needs attention</h2><p>Insights generated from your recorded activity.</p></div></div><div className="business-insight-list">{insights.length?insights.slice(0,5).map(item=><div className="business-insight" key={item.title}><span className="business-insight-icon"><AlertTriangle size={18}/></span><div><strong>{item.title}</strong><p>{item.detail}</p><Link href={item.href}>Review <ArrowUpRight size={14}/></Link></div></div>):<div className="business-empty-insights"><span><TrendingUp size={22}/></span><strong>No priority alerts right now</strong><p>New items will appear as you record business activity.</p></div>}</div></section></div>
  <section className="business-quick-panel"><div><span className="business-eyebrow">WORK FASTER</span><h2>Quick actions</h2><p>Go straight to the tools you use most often.</p></div><div className="business-quick-links"><Link href="/orders/new"><Plus size={17}/> Create an order</Link><Link href="/customers/new"><Users size={17}/> Add a customer</Link><Link href="/payments"><CreditCard size={17}/> Review payments</Link><Link href="/expenses"><Wallet size={17}/> Record expenses</Link></div></section>
 </div>;
}
