'use client';
import {useActionState} from 'react';
import {createCustomer,createOrder,recordPayment,type ActionState} from './actions';
const initial:ActionState={error:'',success:''};
function Result({value}:{value:ActionState}){return <div aria-live="polite">{value.error&&<p className="negative" role="alert">{value.error}</p>}{value.success&&<p style={{color:'#16845b'}}>{value.success}</p>}</div>}
const fieldStyle={width:'100%',padding:'10px 12px',border:'1px solid #d0d5dd',borderRadius:8,background:'#fff'};
const wrapStyle={display:'grid',gap:12,maxWidth:620};
export function CustomerForm(){const [state,action,pending]=useActionState(createCustomer,initial);return <form action={action} style={wrapStyle}><label>Customer name<input style={fieldStyle} name="name" required minLength={2} maxLength={150}/></label><label>Phone<input style={fieldStyle} name="phone" maxLength={40}/></label><label>Email<input style={fieldStyle} type="email" name="email" maxLength={254}/></label><button className="btn primary" disabled={pending}>{pending?'Saving…':'Save customer'}</button><Result value={state}/></form>}
export function OrderForm({customers}:{customers:{id:string;name:string}[]}){const[state,action,pending]=useActionState(createOrder,initial);return <form action={action} style={wrapStyle}><label>Customer<select required name="customer" style={fieldStyle} defaultValue=""><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Product or service description<input name="description" style={fieldStyle} minLength={2} maxLength={200} required/></label><label>Quantity<input type="number" name="quantity" defaultValue="1" min="0.001" step="0.001" style={fieldStyle} required/></label><label>Unit price (₦)<input type="number" name="unit_price" min="0" step="0.01" style={fieldStyle} required/></label><label>Discount (₦)<input type="number" name="discount" min="0" step="0.01" defaultValue="0" style={fieldStyle}/></label><label>Delivery fee (₦)<input type="number" name="delivery" min="0" step="0.01" defaultValue="0" style={fieldStyle}/></label><label>Expected delivery date<input type="date" name="due_date" style={fieldStyle}/></label><p className="muted small">Tax is not charged until tax profiles and legal classifications are verified.</p><button className="btn primary" disabled={pending}>{pending?'Saving…':'Create order'}</button><Result value={state}/></form>}
export function PaymentForm({order,balance}:{order:string;balance:number}){const[state,action,pending]=useActionState(recordPayment,initial);return <form action={action} style={wrapStyle}><input type="hidden" name="order" value={order}/><label>Amount received (₦), maximum {balance.toFixed(2)}<input style={fieldStyle} type="number" name="amount" required min="0.01" max={balance} step="0.01"/></label><label>Payment method<select style={fieldStyle} name="method" required><option value="transfer">Bank transfer</option><option value="cash">Cash</option><option value="pos">POS</option><option value="card">Card, recorded manually</option><option value="other">Other</option></select></label><label>Reference (optional)<input name="reference" style={fieldStyle} maxLength={150}/></label><p className="muted small">Recording only. No payment gateway or online charge is made.</p><button className="btn primary" disabled={pending||balance<=0}>{pending?'Saving…':'Record payment'}</button><Result value={state}/></form>}
