'use client';
import {useActionState} from 'react';
import {createAccount,createPeriod,postJournal,type FinanceState} from './actions';
const initial:FinanceState={error:'',success:''};
function Feedback({state}:{state:FinanceState}){return <p role="status" className={state.error?'small':'small muted'}>{state.error||state.success}</p>}
export function AccountingSetup({accounts,periods}:{accounts:{id:string;code:string;name:string;class:string}[];periods:{id:string;name:string;starts_on:string;ends_on:string;status:string}[]}){
 const [a,accountAction,pa]=useActionState(createAccount,initial);const [b,periodAction,pb]=useActionState(createPeriod,initial);
 return <><form action={accountAction} className="tax-panel"><h3>Add ledger account</h3><label>Code <input name="code" required maxLength={30} placeholder="1000"/></label><label>Account name <input name="name" required maxLength={160} placeholder="Bank account"/></label><label>Class <select name="class">{['asset','liability','equity','income','expense'].map(s=><option key={s} value={s}>{s}</option>)}</select></label><button className="btn primary" disabled={pa}>Create account</button><Feedback state={a}/></form><form action={periodAction} className="tax-panel"><h3>Open accounting period</h3><label>Name <input name="name" required maxLength={80} placeholder="October 2026"/></label><label>Start <input type="date" name="start" required/></label><label>End <input type="date" name="end" required/></label><button className="btn primary" disabled={pb}>Open period</button><Feedback state={b}/></form><p className="muted small">{accounts.length} accounts · {periods.filter(x=>x.status==='open').length} open periods</p></>;
}
export function JournalForm({accounts}:{accounts:{id:string;code:string;name:string}[]}){
 const [state,action,pending]=useActionState(postJournal,initial);return <form action={action} className="tax-panel"><label>Posting date <input type="date" name="date" required/></label><label>Description <input name="description" required maxLength={500}/></label><label>Reference <input name="reference" maxLength={100}/></label><label>Debit account <select name="debit_account" required><option value="">Choose account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>Credit account <select name="credit_account" required><option value="">Choose account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>Amount (NGN) <input type="number" name="amount" min="0.01" step="0.01" required/></label><button className="btn primary" disabled={pending||accounts.length<2}>Post balanced journal</button><Feedback state={state}/><p className="muted small">This form creates equal debit and credit lines. Posted entries are immutable. Tax calculation is not enabled.</p></form>;
}
