import {requireBusinessFeature} from '@/lib/server/authorization';
import Link from 'next/link';import {getWorkspace} from '@/lib/server/workspace';import {money} from '@/lib/format';import {AdjustmentForm} from '../catalog/forms';
async function InternalProtectedPage(){const{client,businessId}=await getWorkspace();const {data,error}=await client.from('products').select('id,name,sku,stock_quantity,minimum_stock,cost_price,track_inventory,active').eq('business_id',businessId).eq('track_inventory',true).eq('active',true).order('name');if(error)throw new Error('Unable to load inventory');const items=data||[];const value=items.reduce((sum,p)=>sum+Number(p.stock_quantity)*Number(p.cost_price),0);const low=items.filter(p=>Number(p.stock_quantity)<=Number(p.minimum_stock));const {data:movements,error:movementsError}=await client.from('inventory_movements').select('id,product_id,movement_type,quantity,notes,created_at').eq('business_id',businessId).order('created_at',{ascending:false}).limit(30);if(movementsError)throw new Error('Unable to load stock history');return <div className="tax-page"><p className="muted small">BUSINESS / INVENTORY</p><h1>Inventory</h1><p className="muted">Physical stock and an auditable record of adjustments.</p><div className="grid grid-3"><section className="tax-panel"><p>Tracked items</p><h2>{items.length}</h2></section><section className="tax-panel"><p>Stock value at cost</p><h2>{money(value)}</h2></section><section className="tax-panel"><p>At or below minimum</p><h2>{low.length}</h2></section></div><section className="tax-panel"><h2>Stock on hand</h2><div className="table-wrap"><table className="table"><thead><tr><th>Product</th><th>On hand</th><th>Minimum</th><th>Cost value</th><th>Status</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td>{p.name}</td><td>{Number(p.stock_quantity)}</td><td>{Number(p.minimum_stock)}</td><td>{money(Number(p.stock_quantity)*Number(p.cost_price))}</td><td>{Number(p.stock_quantity)<=Number(p.minimum_stock)?'Restock':'Healthy'}</td></tr>)}</tbody></table>{!items.length&&<p>No tracked products. <Link href="/products/new">Add one</Link>.</p>}</div></section><section className="tax-panel"><h2>Record stock adjustment</h2><AdjustmentForm items={items.map(p=>({id:p.id,name:p.name}))}/></section><section className="tax-panel"><h2>Recent stock movements</h2><div className="table-wrap"><table className="table"><thead><tr><th>Date</th><th>Product</th><th>Type</th><th>Change</th><th>Reason</th></tr></thead><tbody>{(movements||[]).map(m=><tr key={m.id}><td>{new Date(m.created_at).toLocaleDateString('en-NG')}</td><td>{items.find(p=>p.id===m.product_id)?.name||'Product'}</td><td>{m.movement_type}</td><td>{Number(m.quantity)}</td><td>{m.notes||'—'}</td></tr>)}</tbody></table>{!movements?.length&&<p>No stock movements yet.</p>}</div></section></div>}

export default async function GuardedPage(){
 const check=await requireBusinessFeature('inventory');
 if(!check.allowed)return <section className="tax-page"><h1>Access restricted</h1><p role="alert">{check.reason}</p><a className="btn" href="/upgrade">View available plans</a></section>;
 return <InternalProtectedPage/>;
}
