import Link from 'next/link';
import {getPlatformBrand} from '@/lib/server/branding';
import {getPublicPage} from '@/lib/server/public-cms';
import PublicNav from '@/components/public-nav';
import PublicFooter from '@/components/public-footer';
import {PublicWorkspacePreview} from '@/components/public-workspace-preview';
import {ArrowRight,ArrowUpRight,BarChart3,Boxes,CheckCircle2,ClipboardList,FileCheck2,MessageSquareText,Receipt,ShieldCheck,Users,Wallet,Store,Scissors,BriefcaseBusiness,TrendingUp} from 'lucide-react';
export const revalidate=60;
const features=[
 {icon:Users,title:'Customers, in context',description:'Find customer details, order histories and balances without searching through disconnected records.'},
 {icon:ClipboardList,title:'Sales you can follow',description:'Keep orders, payments and remaining balances connected from the first request to the final collection.'},
 {icon:Boxes,title:'Stock with more clarity',description:'Organise what you sell, review product records and keep an eye on inventory activity.'},
 {icon:Receipt,title:'Paperwork, simplified',description:'Prepare commercial invoices and keep payment acknowledgements within reach.'},
 {icon:BarChart3,title:'Numbers you can understand',description:'Review the business activity behind your decisions with structured records and reports.'},
 {icon:MessageSquareText,title:'One place for the details',description:'Keep the important information about customers, orders and follow-ups organised.'}
];
const solutions=[{icon:Store,name:'Retail & trading',text:'From products on the shelf to money still owed, keep the moving parts together.'},{icon:Scissors,name:'Creative & service teams',text:'Stay close to customer requests, deposits, deliverables and the work ahead.'},{icon:BriefcaseBusiness,name:'Professional businesses',text:'Connect client records, quotes, commercial invoices and incoming payments.'}];
const steps=[{number:'01',title:'Set up your workspace',text:'Add your business details and make one place your source of truth.'},{number:'02',title:'Record work as it happens',text:'Bring in customers, products, sales, payments and everyday expenses.'},{number:'03',title:'See what needs attention',text:'Review balances, activity and available reports without starting from scratch.'}];
export default async function Home(){
 const [brand,home]=await Promise.all([getPlatformBrand(),getPublicPage('home')]);
 // Marketing content contains no private account data: redirect signed-in users via /login.
 return <main id="site-main" className="marketing-site site-refresh"><PublicNav name={brand.name} logo={brand.logo_url} access={'guest'}/>
 <section className="marketing-hero site-hero"><div className="site-hero-art" aria-hidden="true"/><div className="marketing-container marketing-hero-grid"><div className="marketing-hero-copy site-hero-content">
  <div className="site-announcement"><span className="site-announcement-mark"><CheckCircle2 size={14}/></span>{home?.eyebrow||'Everything connected, from day one'}</div>
  <h1>{home?.title||'The clearer way to run your business.'}</h1>
  <p>{home?.description||brand.description}</p>
  <div className="marketing-actions"><Link href="/signup" className="marketing-btn-primary">Start your workspace <ArrowRight size={18}/></Link><Link href="/how-it-works" className="marketing-btn-outline">Explore how it works <ArrowUpRight size={17}/></Link></div>
  <div className="site-hero-highlights"><span><CheckCircle2 size={16}/> Set up at your pace</span><span><CheckCircle2 size={16}/> Works across everyday workflows</span></div>
 </div><PublicWorkspacePreview/></div></section>
 <section className="site-capability-band"><div className="marketing-container"><div className="site-capability-intro">BUILT AROUND EVERYDAY BUSINESS</div><div className="site-capability-items"><span><ClipboardList size={18}/> Orders</span><span><Wallet size={18}/> Payments</span><span><Boxes size={18}/> Products</span><span><Users size={18}/> Customers</span><span><FileCheck2 size={18}/> Records</span></div></div></section>
 <section className="marketing-section site-features-section" id="features"><div className="marketing-container"><div className="site-section-top"><div><span className="marketing-kicker">THE RIGHT DETAILS, TOGETHER</span><h2>Less admin. More momentum.</h2></div><p>Good decisions begin with records you can trust. Get a clearer view of what is happening across the work you do every day.</p></div><div className="marketing-feature-grid">{features.map(f=><article className="marketing-feature" key={f.title}><span className="marketing-feature-icon"><f.icon size={22}/></span><h3>{f.title}</h3><p>{f.description}</p><span className="site-feature-arrow" aria-hidden="true"><ArrowUpRight size={17}/></span></article>)}</div><div className="site-section-link"><Link href="/features">Explore the platform <ArrowRight size={18}/></Link></div></div></section>
 <section className="site-story-section" id="how-it-works"><div className="marketing-container site-story-grid"><div className="site-story-copy"><span className="marketing-kicker">FROM SCATTERED TO STRUCTURED</span><h2>Keep the business moving, without losing the details.</h2><p>Turn everyday activity into a more organised routine. So when you need to check an order, follow up on a balance or review an expense, you know where to look.</p><Link href="/how-it-works" className="marketing-text-link">See how BusinessOS works <ArrowUpRight size={18}/></Link><div className="site-story-quote"><ShieldCheck size={21}/><span>Your records stay organised by business, with role-based access designed for growing teams.</span></div></div><div className="site-process-card"><span className="site-process-heading">A clearer daily routine</span>{steps.map(step=><div className="site-process-step" key={step.number}><span className="site-process-number">{step.number}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></div>)}</div></div></section>
 <section className="marketing-section site-solutions-section" id="solutions"><div className="marketing-container"><div className="marketing-section-heading"><span className="marketing-kicker">FLEXIBLE BY NATURE</span><h2>One foundation. Different ways of working.</h2><p>Whether your business sells products, provides services or manages both, stay close to what matters without forcing everything into the same process.</p></div><div className="site-solution-grid">{solutions.map((s,index)=><Link href="/solutions" className={`site-solution-card site-solution-${index}`} key={s.name}><div className="site-solution-icon"><s.icon size={27}/></div><span className="site-solution-meta">BUSINESS WORKSPACE</span><h3>{s.name}</h3><p>{s.text}</p><span className="site-solution-bottom">Explore solution <ArrowUpRight size={17}/></span></Link>)}</div></div></section>
 {home?.sections?.filter(s=>s.heading&&s.body&&!s.heading.startsWith('Everything you need')).map((s,i)=><section key={i} className="site-custom-block"><div className="marketing-container"><span className="marketing-kicker">FROM OUR TEAM</span><h2>{s.heading}</h2><p>{s.body}</p></div></section>)}
 <section className="site-bottom-cta"><div className="marketing-container"><div className="site-cta-inner"><div><span className="marketing-kicker">READY FOR A CLEARER WAY?</span><h2>Make more room for the work that matters.</h2><p>Start organising the everyday details of your business in one place.</p></div><Link className="marketing-btn-primary" href="/signup">Create your workspace <ArrowRight size={18}/></Link></div></div></section>
 <PublicFooter name={brand.name} tagline={brand.tagline} email={brand.support_email}/></main>;
}
