import Link from 'next/link';
import {getPlatformBrand} from '@/lib/server/branding';
import PublicNav from '@/components/public-nav';
import {getPublicPage} from '@/lib/server/public-cms';
import {ArrowRight,ArrowUpRight,BarChart3,Boxes,Calculator,Check,CheckCircle2,ChevronRight,Clock3,FileText,Headphones,Layers3,MessageSquareText,Receipt,ShieldCheck,ShoppingBag,TrendingUp,Users,Wallet} from 'lucide-react';
const areas=[{icon:ShoppingBag,title:'Sales & orders',description:'Know what has been ordered, paid for, delivered and what is still outstanding.'},{icon:Calculator,title:'Accounting made practical',description:'Keep your records organised, from daily expenses to journals and financial reports.'},{icon:Receipt,title:'Tax records & guidance',description:'Understand tax classifications, organise your records and prepare for review.'},{icon:Boxes,title:'Products & inventory',description:'Track what you sell, stock movements and items that need attention.'},{icon:MessageSquareText,title:'Customers & communication',description:'Keep customer information and conversations in a single organised workspace.'},{icon:BarChart3,title:'Business insights',description:'Spot trends in sales, collections, expenses and business performance.'}];
const audiences=[{title:'Retail & trading',detail:'Manage stock, daily sales, suppliers and customer balances.'},{title:'Fashion & beauty',detail:'Track appointments, made-to-order jobs, deposits and delivery dates.'},{title:'Food & hospitality',detail:'Organise orders, ingredients, expenses and business records.'},{title:'Professional services',detail:'Send quotations, track projects and manage your clients.'}];
export default async function Home(){const [brand,home]=await Promise.all([getPlatformBrand(),getPublicPage('home')]);return <main className="marketing-site">
 <PublicNav name={brand.name} logo={brand.logo_url}/>
 <section className="marketing-hero"><div className="marketing-container marketing-hero-grid"><div className="marketing-hero-copy"><div className="marketing-eyebrow"><span className="marketing-eyebrow-dot"/> {home?.eyebrow||'One workspace for your entire business'}</div><h1>{home?.title||'Run your business with clarity. Grow with confidence.'}</h1><p>{home?.description||brand.description}</p><div className="marketing-actions"><Link className="marketing-btn-primary" href="/signup">Get started <ArrowRight size={18}/></Link><a className="marketing-btn-outline" href="#how-it-works">See how it works <ChevronRight size={17}/></a></div><div className="marketing-hero-note"><CheckCircle2 size={17}/> Built for small and growing businesses <span>•</span> Simple to get started</div></div>
 <div className="marketing-preview" aria-label="Illustration of the business dashboard"><div className="preview-window"><div className="preview-left"><div className="preview-mini-logo"><Layers3 size={18}/></div><div className="preview-nav selected">▦ <span>Overview</span></div><div className="preview-nav">▤ <span>Orders</span></div><div className="preview-nav">◫ <span>Customers</span></div><div className="preview-nav">◈ <span>Accounting</span></div><div className="preview-nav">▥ <span>Inventory</span></div><div className="preview-nav">◷ <span>Reports</span></div></div><div className="preview-main"><div className="preview-top"><span>Overview</span><span className="preview-avatar">SB</span></div><div className="preview-welcome">Your business at a glance <span>Illustrative preview</span></div><div className="preview-stats"><div><span>Total sales</span><strong>₦4.85m</strong><small>↗ Sales recorded</small></div><div><span>Received</span><strong>₦3.64m</strong><small>↗ Collected payments</small></div><div><span>Outstanding</span><strong>₦1.21m</strong><small>Awaiting collection</small></div></div><div className="preview-chart-card"><div className="preview-chart-title">Sales overview <span>Last 6 months</span></div><div className="preview-bars">{[42,55,48,74,65,89,72,100,86,96,78,91].map((h,i)=><div key={i}><span style={{height:`${h}%`}}/></div>)}</div><div className="preview-months"><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span><span>Oct</span></div></div><div className="preview-tasks"><span>Recent activity</span><div><i/>Customer order recorded <strong>₦45,000</strong></div><div><i/>Part payment received <strong>₦20,000</strong></div></div></div></div><div className="preview-floating"><Check size={16}/> Everything in one place</div></div></div></section>
 <section className="marketing-trust"><div className="marketing-container"><span>DESIGNED TO SUPPORT EVERYDAY BUSINESS WORK</span><div className="marketing-trust-items"><div><ShieldCheck size={20}/> Organised records</div><div><Clock3 size={20}/> Less manual work</div><div><Wallet size={20}/> Financial clarity</div><div><Headphones size={20}/> Customer focus</div></div></div></section>
 <section className="marketing-section" id="features"><div className="marketing-container"><div className="marketing-section-heading"><span className="marketing-kicker">ONE CONNECTED PLATFORM</span><h2>Everything you need to keep business moving.</h2><p>No more switching between notebooks, scattered messages and separate spreadsheets to understand what is happening.</p></div><div className="marketing-feature-grid">{areas.map((item)=><article key={item.title} className="marketing-feature"><span className="marketing-feature-icon"><item.icon size={23}/></span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div></div></section>
 <section className="marketing-section marketing-section-muted" id="how-it-works"><div className="marketing-container marketing-split"><div><span className="marketing-kicker">BUILT FOR THE WAY YOU WORK</span><h2>Spend less time chasing records. More time moving forward.</h2><p>Whether you are just starting out or have a team, the platform helps you bring everyday business activities into a consistent process.</p><Link className="marketing-text-link" href="/signup">Create your workspace <ArrowUpRight size={17}/></Link></div><div className="marketing-steps">{[{n:'01',h:'Set up your business',d:'Add your business information and tell us what you sell.'},{n:'02',h:'Organise daily activities',d:'Keep customers, products, orders, payments and expenses together.'},{n:'03',h:'Understand your numbers',d:'See records, balances and reporting in one organised view.'}].map(s=><div className="marketing-step" key={s.n}><span>{s.n}</span><div><h3>{s.h}</h3><p>{s.d}</p></div></div>)}</div></div></section>
 <section className="marketing-section" id="solutions"><div className="marketing-container"><div className="marketing-section-heading"><span className="marketing-kicker">FLEXIBLE BY DESIGN</span><h2>Made for different kinds of businesses.</h2><p>Products, services or a little of both. Build a workspace that fits the way your business runs.</p></div><div className="marketing-solutions">{audiences.map(a=><article key={a.title}><h3>{a.title}</h3><p>{a.detail}</p><CheckCircle2 size={21}/></article>)}</div></div></section>
 <section className="marketing-section marketing-section-muted" id="why-us"><div className="marketing-container marketing-split"><div><span className="marketing-kicker">A SMARTER WAY TO MANAGE</span><h2>Powerful features. A simpler experience.</h2><p>You should not need a degree in accounting or a complicated setup process to keep good business records.</p><div className="marketing-benefits">{['Clear payment and balance tracking','Guided business setup and records','Financial reports for better decisions','Space to grow with your team'].map(x=><div key={x}><CheckCircle2 size={18}/>{x}</div>)}</div></div><div className="marketing-value-panel"><span>WHAT MATTERS MOST</span><h3>Know what you sold. Know what you received. Know what comes next.</h3><div className="marketing-value-row"><TrendingUp size={20}/> Better visibility into everyday business</div><div className="marketing-value-row"><Users size={20}/> Stronger customer relationships</div><div className="marketing-value-row"><FileText size={20}/> More organised business records</div></div></div></section>
 <section className="marketing-section" id="faqs"><div className="marketing-container marketing-faq"><div><span className="marketing-kicker">FREQUENTLY ASKED QUESTIONS</span><h2>Good to know before you begin.</h2></div><div>{[{q:'Who is this platform for?',a:'It is designed for small and growing businesses that sell products, provide services or do both.'},{q:'Do I need accounting experience?',a:'No. The product is designed to help you record normal business activities in everyday language, while providing accounting structures for professional review.'},{q:'Can I record part payments?',a:'Yes. The platform is being developed to track deposits, completed payments and remaining order balances.'},{q:'Does the platform file my taxes automatically?',a:'No. Tax recordkeeping and classification features are being developed, but regulatory filing and tax payment services are not active.'}].map(f=><details key={f.q}><summary>{f.q}<span>+</span></summary><p>{f.a}</p></details>)}</div></div></section>
 <section className="marketing-final"><div className="marketing-container"><span className="marketing-kicker">TAKE THE NEXT STEP</span><h2>Your business deserves a better way to run.</h2><p>Bring your important records together and build a clearer picture of your business.</p><Link href="/signup" className="marketing-btn-primary">Create your account <ArrowRight size={18}/></Link></div></section>
 <footer className="marketing-footer"><div className="marketing-container"><div className="marketing-footer-top"><div><strong>{brand.name}</strong><p>{brand.tagline}</p></div><div><strong>Platform</strong><Link href="/features">Features</Link><Link href="/solutions">Solutions</Link><Link href="/pricing">Pricing</Link></div><div><strong>Account</strong><Link href="/login">Sign in</Link><Link href="/signup">Get started</Link></div><div><strong>Help</strong><Link href="/resources">Resources</Link><Link href="/contact">Contact</Link>{brand.support_email&&<a href={`mailto:${brand.support_email}`}>Contact support</a>}</div></div><div className="marketing-footer-bottom"><span>© {new Date().getFullYear()} {brand.name}. All rights reserved.</span><span>Built for businesses with ambition.</span></div></div></footer>
 </main>}
