import {redirect} from 'next/navigation';
import {getServerSupabase} from '@/lib/server/supabase';
import {saveBusinessProfile} from './actions';
export const dynamic='force-dynamic';
export default async function Settings(){const client=await getServerSupabase();if(!client)redirect('/login');const {data:{user}}=await client.auth.getUser();if(!user)redirect('/login');
 const {data:member}=await client.from('business_members').select('business_id,role').eq('user_id',user.id).limit(1).maybeSingle();if(!member)redirect('/onboarding');
 const {data:business,error}=await client.from('businesses').select('name,category,phone,whatsapp,description,currency').eq('id',member.business_id).maybeSingle();
 return <div className="tax-page"><p className="small muted">BUSINESS / SETTINGS</p><h1>Business settings</h1><p className="muted">Your business identity is separate from the platform name and branding.</p>{error&&<p role="alert">Business profile could not be loaded.</p>}
 <section className="tax-panel"><h2>Business profile</h2><form action={saveBusinessProfile}><input type="hidden" name="business_id" value={member.business_id}/><div className="form-grid"><label className="field">Business name<input name="name" required minLength={2} maxLength={120} defaultValue={business?.name||''} disabled={member.role!=='owner'}/></label><label className="field">Category<input name="category" maxLength={120} defaultValue={business?.category||''} disabled={member.role!=='owner'}/></label><label className="field">Phone<input name="phone" maxLength={40} defaultValue={business?.phone||''} disabled={member.role!=='owner'}/></label><label className="field">WhatsApp<input name="whatsapp" maxLength={40} defaultValue={business?.whatsapp||''} disabled={member.role!=='owner'}/></label><label className="field full">Description<textarea name="description" rows={3} maxLength={1000} defaultValue={business?.description||''} disabled={member.role!=='owner'}/></label></div>{member.role==='owner'?<button className="btn btn-primary" type="submit">Save business settings</button>:<p>Only the business owner can update these settings.</p>}</form><p className="small muted">Currency: {business?.currency||'NGN'}. Financial defaults and tax treatments are managed separately.</p></section></div>}
