'use client';
import {useActionState,useState} from 'react';
import {openCashierShift,recordCashMovement,closeCashierShift,reviewCashierShift,type CashierActionState} from './shift-actions';
import Link from 'next/link';
const initial:CashierActionState={ok:false,message:''};
function ActionMessage({state}:{state:CashierActionState}){return <>{state.message&&<p role="status" className={state.ok?'positive':'negative'}>{state.message}</p>}{state.shiftId&&state.ok&&<p><Link href={`/pos/shifts/${state.shiftId}`} className="btn">View shift report</Link></p>}</>}
export function OpenShiftForm(){const [state,action,pending]=useActionState(openCashierShift,initial);return <form action={action} className="comms-form cashier-form"><label>Opening cash float (₦)<input name="opening_cash" type="number" step="0.01" min="0" required defaultValue="0.00"/></label><p className="small muted">Count physical cash before opening. You can only have one active shift in a business at a time.</p><button className="btn btn-primary" disabled={pending}>{pending?'Opening…':'Open my cashier shift'}</button><ActionMessage state={state}/></form>}
export function MovementForm({shiftId}:{shiftId:string}){const [state,action,pending]=useActionState(recordCashMovement,initial);return <form action={action} className="comms-form cashier-form"><input type="hidden" name="shift_id" value={shiftId}/><label>Cash movement<select name="kind"><option value="cash_in">Cash in (add physical cash)</option><option value="cash_out">Cash out (remove physical cash)</option></select></label><label>Amount (₦)<input name="amount" type="number" step="0.01" min="0.01" required/></label><label>Reason (minimum 10 characters)<textarea name="reason" minLength={10} maxLength={500} required rows={2} placeholder="e.g. Change float added from safe or verified cash refund"/></label><label>Unique voucher/reference<input name="reference" minLength={3} maxLength={150} required placeholder="e.g. CASH-OUT-0042"/></label><button disabled={pending} className="btn btn-primary">{pending?'Recording…':'Record cash movement'}</button><ActionMessage state={state}/></form>}
export function CloseShiftForm({shiftId}:{shiftId:string}){const [state,action,pending]=useActionState(closeCashierShift,initial);return <form action={action} className="comms-form cashier-form"><input type="hidden" name="shift_id" value={shiftId}/><label>Physically counted closing cash (₦)<input name="counted_cash" type="number" step="0.01" min="0" required/></label><label>Closing remarks<textarea name="note" maxLength={500} rows={2} placeholder="Mention cash shortages, refunds or discrepancies"/></label><label className="bo-checkbox"><input type="checkbox" name="verified" value="yes" required/> I have counted the physical cash and reviewed all cash-ins, cash-outs and recorded refunds.</label><button disabled={pending} className="btn btn-primary">{pending?'Closing…':'Close shift and record variance'}</button><ActionMessage state={state}/></form>}
export function ReviewShiftForm({shiftId,variance}:{shiftId:string;variance:number}){const [state,action,pending]=useActionState(reviewCashierShift,initial);const [decision,setDecision]=useState('approve');return <form action={action} className="comms-form cashier-form"><input name="shift_id" type="hidden" value={shiftId}/><label>Supervisor decision<select name="decision" value={decision} onChange={e=>setDecision(e.target.value)}><option value="approve">Review and accept recorded result</option><option value="flag">Flag for investigation</option></select></label><label>Management review note<textarea name="note" rows={3} minLength={variance!==0||decision==='flag'?10:undefined} required={variance!==0||decision==='flag'} maxLength={500} placeholder="Explain all variances or flagged decisions (at least 10 characters)"/></label><label className="bo-checkbox"><input name="reviewed" type="checkbox" value="yes" required/> I have reviewed the cashier's figures and underlying cash movements.</label><button disabled={pending} className="btn btn-primary">{pending?'Saving…':'Save management review'}</button><ActionMessage state={state}/></form>}
