import Link from 'next/link';
import {requirePlatformAdmin} from '@/lib/server/supabase';
import {ReviewSupportForm} from './review-form';
export const dynamic='force-dynamic';
type Ticket={id:string;business_id:string;business_name:string;requested_by:string;kind:string;subject:string;details:string;target_user_id:string|null;proposed_role:string|null;status:string;admin_response:string|null;created_at:string};
export default async function PlatformSupport(){
 const a=await requirePlatformAdmin();if(!a)return <main className="admin-access"><h1>Administrator login required</h1><Link href="/login">Sign in</Link></main>;
 const {data,error}=await a.client.rpc('platform_support_queue');
 const tickets=((data||[]) as Ticket[]);const open=tickets.filter(t=>t.status==='open');
 return <main className="admin-area"><header className="admin-header"><div><span className="badge badge-brand">PLATFORM ADMIN / ASSISTANCE</span><h1>Business support & role requests</h1><p>Respond to customers and assist business owners with approved staff changes without accessing their passwords or impersonating users.</p></div><Link href="/admin/businesses" className="btn">Business directory</Link></header>
 {error?<section className="card card-pad" role="alert"><h2>Support queue unavailable</h2><p>Confirm SQL 042 and administrator permissions. {error.message}</p></section>:<><div className="grid grid-3"><section className="card card-pad"><p className="metric-label">Open requests</p><h2>{open.length}</h2></section><section className="card card-pad"><p className="metric-label">Role requests</p><h2>{open.filter(t=>t.kind==='role_change').length}</h2></section><section className="card card-pad"><p className="metric-label">Recent requests loaded</p><h2>{tickets.length}</h2><p className="small muted">Latest 80 maximum</p></section></div><div style={{display:'grid',gap:14,marginTop:20}}>{open.map(t=><section className="card card-pad" key={t.id}><div className="admin-header" style={{marginBottom:10}}><div><span className="badge">{t.kind==='role_change'?'Role assistance':'General support'}</span><h2 style={{margin:'9px 0 4px'}}>{t.subject}</h2><p>{t.business_name} · {new Date(t.created_at).toLocaleString('en-NG')}</p></div><Link href={`/admin/businesses/${t.business_id}`} className="btn">Business details</Link></div><p>{t.details}</p>{t.kind==='role_change'&&<p className="small muted">Owner requested target: {t.target_user_id} · Role: <strong>{t.proposed_role}</strong>. The database rechecks current owner consent and target membership before applying any change.</p>}<ReviewSupportForm id={t.id} roleChange={t.kind==='role_change'}/></section>)}{open.length===0&&<section className="card card-pad"><h2>No support requests awaiting review</h2><p className="muted">New customer requests will appear here.</p></section>}</div></>}
 </main>;
}
