'use client';
import {useMemo,useState} from 'react';
import {calculateVat,formatMinor,type Treatment} from '@/lib/tax/engine';
type Item={id:string;name:string;kind:string;treatment:string;approved:boolean};
export function VatEstimator({items}:{items:Item[]}){
 const [selected,setSelected]=useState<Record<string,{quantity:string;price:string}>>({});
 const [eligible,setEligible]=useState(false);
 const result=useMemo(()=>{try{const lines=items.filter(i=>selected[i.id]).map(i=>({name:i.name,quantity:selected[i.id].quantity,unitPrice:selected[i.id].price,treatment:i.treatment as Treatment,approved:i.approved}));return lines.length?calculateVat(lines,eligible):null;}catch{return null;}},[items,selected,eligible]);
 return <div><p className="muted small">Enter a price for each item to include. No invoices or ledger entries will be created.</p><label><input type="checkbox" checked={eligible} onChange={e=>setEligible(e.target.checked)}/> VAT charging obligation independently confirmed (preview only)</label><div className="table-wrap"><table className="table"><thead><tr><th>Item</th><th>Tax status</th><th>Quantity</th><th>Unit price (₦)</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.name}</td><td>{i.approved?i.treatment:'Review required'}</td><td><input aria-label={`${i.name} quantity`} type="number" min="1" step="1" value={selected[i.id]?.quantity||'1'} onChange={e=>setSelected(v=>({...v,[i.id]:{quantity:e.target.value,price:v[i.id]?.price||''}}))}/></td><td><input aria-label={`${i.name} price`} type="number" min="0" step="0.01" value={selected[i.id]?.price||''} placeholder="0.00" onChange={e=>setSelected(v=>({...v,[i.id]:{quantity:v[i.id]?.quantity||'1',price:e.target.value}}))}/></td></tr>)}</tbody></table></div>
 {result?<div className="tax-notice"><p>Net: <strong>{formatMinor(result.netMinor)}</strong></p><p>VAT preview: <strong>{formatMinor(result.vatMinor)}</strong></p><p>Total: <strong>{formatMinor(result.totalMinor)}</strong></p><strong>{result.status==='review_required'?'REVIEW REQUIRED — not suitable for invoicing':'PROVISIONAL ESTIMATE — not authorised for posting'}</strong></div>:<p className="muted small">Enter valid item prices to see an estimate.</p>}
 <p className="muted small">Classification approval and transaction-date eligibility must be enforced by the server for a production invoice. This client estimator is informational only.</p></div>;
}
